name: vetstan
description: A new Flutter project.
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  provider: ^6.1.5
  shared_preferences: ^2.3.3
  flutter_localizations:
    sdk: flutter

  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  intl: ^0.19.0
  flutter_tts: ^3.8.5
  path_provider: ^2.1.5
  cached_network_image: ^3.3.0
  http: ^1.2.1
  loading_animation_widget: ^1.2.0+4
  photo_view: ^0.14.0
  shimmer: ^3.0.0
  permission_handler: ^11.1.0
  dio: ^5.4.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_svg: ^2.0.9
  syncfusion_flutter_pdfviewer: ^28.1.35
  google_sign_in: ^6.1.6
  timeago: ^3.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_phoenix: ^1.1.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Icon/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/stool/
    - assets/images/persons/
    - assets/translations/
    - assets/data/instruments.json
    - assets/instruments/
    - assets/Icons/  # Feature icons
    - assets/icon/   # App logo
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: NRT
      fonts:
        - asset: assets/fonts/Nrt_bold.ttf
          weight: 700
    - family: K24
      fonts:
        - asset: assets/fonts/k24.ttf
    - family: Speda
      fonts:
        - asset: assets/fonts/speda.ttf
